version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
            - mongo
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: gustavo
            ME_CONFIG_BASICAUTH_PASSWORD: gustavo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: gustavo
        links:
            - mongo
        networks:
            - app-network
    
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: gustavo
        ports:
            - "27017:27017"
        volumes:
            - .docker/dbdata:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge